# Generated by Django 4.2.1 on 2023-06-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chataki", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personality_type", models.CharField(max_length=200)),
                ("personality_id", models.IntegerField(default=0)),
            ],
        ),
    ]
